name: mylang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mylang-image .

      - name: Run Docker container & build
        run: docker run -it -d -v $(pwd):/home/ --name mylang mylang-image make build

      - name: See logs
        run: docker logs -f mylang

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t mylang-image .

      - name: Run Docker container & test
        run: docker run -it -d -v $(pwd):/home/ --name mylang mylang-image make test

      - name: See logs
        run: docker logs -f mylang