# This is a basic workflow to help you get started with Actions

name: mylang

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mylang-image .

      - name: Run Docker container
        run: docker run -it -d -v $(pwd):/home/ --name mylang mylang-image

      - name: Build inside of the container
        run: docker exec -d mylang make build

      - name: See logs
        run: docker logs -f mylang

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t mylang-image .

      - name: Run Docker container
        run: docker run -it -d -v $(pwd):/home/ --name mylang mylang-image

      - name: Test
        run: docker exec -id mylang make test

      - name: See logs
        run: docker logs -f mylang